### PR TITLE
Fix: Disposed logs

### PR DESCRIPTION
**Pull request by 0xc0d**
Added `Send` call to Event, without it, the logs won't show up. `Send` is equivalent to calling `Msg("")`.

### CODE REVIEW

**Comment by chriswalz** [comment]
So these lines are not actually logging anything? What caused you to make this change?

**Comment by 0xc0d** [comment]
No actually! without `Msg` nothing will happen!
Nothing happened. Just reviewing the code, and found this issue!

**Comment by chriswalz** [comment]
@0xc0d I verified your changes, that's a bit embarrassing :P.  Thanks for the PR!

**Comment by 0xc0d** [comment]
Anytime!
Don't worry! I think the design is so confusing xD!

**Pull request merged**
