### PR TITLE
Added Chocolatey Install Instructions

### PR DESCRIPTION
**Pull request by digitalcoyote**
# Installation via Chocolatey
Chocolatey allows installing bit and git in a single command (if git is not already installed). It is my preferred package manager on Windows. Microsoft has their own package manager now, but it requires an msi installer (currently).

https://chocolatey.org/packages/bit-git/0.9.10

## Maintenance
- I have an AU repo that is currently setup to maintain this package (no changes/extra work for you).
- I can add you as a maintainer in Chocolatey so that you have basic management rights to the package (delist versions, upload versions etc). This would make it easier to take over the package if anything happened to me and the CI went down.

## Questions, Concerns, Etc
- Installs bit Directly to the path and takes care of upgrades/downgrades/uninstalls
- When I ran it after an install, it failed to recognize the current repo as a git repo (might mean changes need to be made to the install script in the package)

## Should Not Be Merged Before Moderators Approve
Before moderator approval, the package will only be installable if the user explicitly sets the version to install. It will also be hidden from searches until at least one version is approved.

### CODE REVIEW

**Comment by chriswalz** [comment]
This appears to install this https://chocolatey.org/packages/bit

Which is a program by the same name but related to this bit

**Comment by digitalcoyote** [comment]
I set the title and the I'd differently (I do not know that moderation allows it, but the nuspec verification appears to). The Files > chocolateyinstsll.ps1 link should show that this is downloading directly from your released page. Are you getting redirected to bit instead of bit-git? If so I need to update the title to match

**Comment by chriswalz** [comment]
@digitalcoyote I haven't actually tried it but it appears it would install another program. My guess is the installation will be `choco install bit-git`

**Comment by chriswalz** [comment]
@digitalcoyote Also, thanks for setting this up!

**Comment by digitalcoyote** [comment]
... <insert face palm>

Yeah... I messed that up in the instructions. I'll correct it. Lol I thought there was some confusion on the package details page or that it was redirecting. 

Thanks for catching that.

**Comment by chriswalz** [comment]
@digitalcoyote looks like it's still in review :/

**Comment by digitalcoyote** [comment]
> @digitalcoyote looks like it's still in review :/

It generally takes at least 2 weeks for the first version of a package to get approved. Hacktoberfest seems to put a lot more packages in their queue in October and increases the wait through November (all review is done by volunteers).

You can view the moderator queue [here](https://chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) but I don't know what sort order they use.

**Comment by digitalcoyote** [comment]
Got a notification that the first version has been approved so it should be listed publicly now.

**Comment by chriswalz** [comment]
@digitalcoyote it's been a long time coming! merged

**Pull request merged**
